
app = "mesh-executor-fly"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  MESH_TOKEN = "holon-mesh-internal-2026"
  PORT = "3080"

[[services]]
  internal_port = 3080
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "5s"
    path = "/health"
